language: node_js
node_js:
  - "0.10"
before_install:
  - rvm use 1.9.3
install:
  - travis_retry npm install -g grunt-cli
  - travis_retry npm install
  - travis_retry gem install --no-document "jekyll:~>2.2.0" "sass:~>3.3.12" "scss-lint:~>0.24.1"
matrix:
  fast_finish: true
notifications:
  slack: heybb:51atQXKR2rpnbohAZ0X1vNbE
  
